/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_computerenhance_sim86_Decoder */

#ifndef _Included_com_computerenhance_sim86_Decoder
#define _Included_com_computerenhance_sim86_Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_computerenhance_sim86_Decoder
 * Method:    version
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_computerenhance_sim86_Decoder_version
  (JNIEnv *, jclass);

/*
 * Class:     com_computerenhance_sim86_Decoder
 * Method:    decode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_computerenhance_sim86_Decoder_decode
  (JNIEnv *, jobject);

/*
 * Class:     com_computerenhance_sim86_Decoder
 * Method:    registerName
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_computerenhance_sim86_Decoder_registerName
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_computerenhance_sim86_Decoder
 * Method:    mnemonic
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_computerenhance_sim86_Decoder_mnemonic
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
